#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include "headers/abb.h"
#include "headers/avl.h"

FILE* open_file(char* path, char* mode);

void swap(int *a, int *b) {
    int aux = *a;
    *a = *b;
    *b = aux;
}

int main () {

	FILE* data = open_file("data.txt", "w");
	
    clock_t t;
    t = clock();

	struct binary_tree_avl* AVL = create_empty_binary_tree_avl();
	struct binary_tree* ABB = create_empty_binary_tree();
	struct binary_tree* ABB_sorted = create_empty_binary_tree();

	int num, i, j;

	printf("Numero de items a serem inseridos: ");
	int items;
	scanf("%d", &items);
	// Number of items that will be added on the trees.

	printf("Digite o numero de buscas: ");
	int searchs;
	scanf("%d", &searchs);
	// Number of tests (searchs) that will be done with random numbers (can repeat).

	srand(time(NULL));

	int *array = malloc(sizeof(int)*items);
	
	for(i = 0; i < items; i++){
		array[i] = i;
		ABB_sorted = add(ABB_sorted, i);
		// Inserts sorted numbers in the ABB sorted tree.
	}
	// Create an array of size 'items' with every different numbers (sorted).

	for (i = items-1; i > 0; i--) { // Fisher–Yates shuffle algorithm.
		j = ((rand() << 8) | rand()) % i;
		swap(&array[i], &array[j]);
	}
	// Shuffles the array

	for(i = 0; i < items; i++) {
		AVL = add_avl(AVL, array[i]);
		ABB = add(ABB, array[i]);	
	}
	// Inserts a random item to the ABB and AVL (never repeated).

	free(array);

	fprintf(data, "ABBs ABB AVL\n");
	// Header

	int compareABB_sorted = 0;
	int compareABB = 0;
	int compareAVL = 0;

	for(i = 0; i < searchs; i++){
		
		int num = ((rand() << 8) | rand()) % items; 
		// Sets a random number between 0 and 'items'.
		// Shiftbit to increase the size of the random number generated by function rand().

		search(ABB_sorted, num, &compareABB_sorted);
		search(ABB, num, &compareABB);
		search_avl(AVL, num, &compareAVL);
		// Do the search on all the 3 trees get how many comparisons was done in each one.

		fprintf(data, "%d %d %d\n", compareABB_sorted, compareABB, compareAVL);
		// Print all of them in the file.

		printf("Comparisons (ABBsorted|ABB|AVL): (%d|%d|%d), Number %d\n", compareABB_sorted, compareABB, compareAVL, num);

		compareABB_sorted = 0;
		compareABB = 0;
		compareAVL = 0;
	}

	fclose(data);
	AVL = clear_avl(AVL);
	ABB = clear(ABB);
	ABB_sorted = clear(ABB_sorted);
	// Free all.

	t = clock() - t;
	double time_taken = ((double)t)/CLOCKS_PER_SEC;
	printf("Took %.2f seconds to execute \n", time_taken);
	// Time counter.

	return 0;
}

FILE* open_file(char* path, char* mode) {

    FILE *f = fopen(path, mode);

    if (f == NULL) {
        printf("Error opening file %s.\n", path);
        exit(1);
    }

    return f;
}

